-- ============================================================
-- ENTERPRISE LAKEHOUSE — SNOWFLAKE SETUP
-- Author : Ram Karne | Enterprise Data Architect
-- Purpose: Warehouse, database, schema, and RBAC configuration
-- ============================================================

-- ── WAREHOUSES ──────────────────────────────────────────────
-- Separate warehouses per workload for cost isolation

CREATE WAREHOUSE IF NOT EXISTS WH_INGESTION
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND   = 120
  AUTO_RESUME    = TRUE
  COMMENT        = 'Fivetran / Airflow ingestion workload';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND   = 120
  AUTO_RESUME    = TRUE
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY = 'ECONOMY'
  COMMENT        = 'DBT transformation workload — multi-cluster for concurrent runs';

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  COMMENT        = 'BI tools (Power BI, Tableau) — short auto-suspend to control cost';

CREATE WAREHOUSE IF NOT EXISTS WH_CORTEX
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND   = 120
  AUTO_RESUME    = TRUE
  COMMENT        = 'Snowflake Cortex AI workloads — data quality and ML scoring';

-- ── DATABASES & SCHEMAS (Medallion) ─────────────────────────

CREATE DATABASE IF NOT EXISTS LAKEHOUSE;

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.BRONZE
  COMMENT = 'Raw ingestion layer — no transformations, full history retained';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.SILVER
  COMMENT = 'Cleansed, deduplicated, MDM-resolved layer';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.GOLD
  COMMENT = 'Business-ready dimensional models for BI and ML';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.MDM
  COMMENT = 'Master Data Management — golden records for contacts, accounts, products';

CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.GOVERNANCE
  COMMENT = 'Data quality rules, audit logs, lineage metadata';

-- ── ROLES (RBAC) ─────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS ROLE_DATA_ARCHITECT
  COMMENT = 'Full access — data architects and senior engineers';

CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER
  COMMENT = 'Read/write on Bronze and Silver; read on Gold';

CREATE ROLE IF NOT EXISTS ROLE_DATA_ANALYST
  COMMENT = 'Read-only on Silver and Gold';

CREATE ROLE IF NOT EXISTS ROLE_BI_CONSUMER
  COMMENT = 'Read-only on Gold — Power BI, Tableau service accounts';

CREATE ROLE IF NOT EXISTS ROLE_MDM_STEWARD
  COMMENT = 'Read/write on MDM schema — data stewards only';

-- Role hierarchy
GRANT ROLE ROLE_DATA_ENGINEER TO ROLE ROLE_DATA_ARCHITECT;
GRANT ROLE ROLE_DATA_ANALYST   TO ROLE ROLE_DATA_ENGINEER;
GRANT ROLE ROLE_BI_CONSUMER    TO ROLE ROLE_DATA_ANALYST;

-- ── GRANTS ───────────────────────────────────────────────────

-- Architect: full access
GRANT ALL PRIVILEGES ON DATABASE LAKEHOUSE TO ROLE ROLE_DATA_ARCHITECT;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE LAKEHOUSE TO ROLE ROLE_DATA_ARCHITECT;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE ROLE_DATA_ARCHITECT;
GRANT USAGE ON WAREHOUSE WH_CORTEX    TO ROLE ROLE_DATA_ARCHITECT;

-- Engineer: Bronze + Silver write, Gold read
GRANT USAGE ON DATABASE LAKEHOUSE TO ROLE ROLE_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA LAKEHOUSE.BRONZE  TO ROLE ROLE_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA LAKEHOUSE.SILVER  TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT         ON ALL TABLES IN SCHEMA LAKEHOUSE.GOLD TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_INGESTION TO ROLE ROLE_DATA_ENGINEER;

-- Analyst: Silver + Gold read
GRANT USAGE  ON DATABASE LAKEHOUSE TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA LAKEHOUSE.SILVER TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA LAKEHOUSE.GOLD   TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ROLE_DATA_ANALYST;

-- BI Consumer: Gold only
GRANT USAGE  ON DATABASE LAKEHOUSE TO ROLE ROLE_BI_CONSUMER;
GRANT SELECT ON ALL TABLES IN SCHEMA LAKEHOUSE.GOLD TO ROLE ROLE_BI_CONSUMER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ROLE_BI_CONSUMER;

-- MDM Steward: MDM schema only
GRANT USAGE      ON DATABASE LAKEHOUSE       TO ROLE ROLE_MDM_STEWARD;
GRANT ALL PRIVILEGES ON SCHEMA LAKEHOUSE.MDM TO ROLE ROLE_MDM_STEWARD;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS        TO ROLE ROLE_MDM_STEWARD;

-- ── FUTURE GRANTS (auto-apply to new tables) ─────────────────
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAKEHOUSE.GOLD   TO ROLE ROLE_BI_CONSUMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAKEHOUSE.SILVER TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAKEHOUSE.GOLD   TO ROLE ROLE_DATA_ANALYST;

-- ── RESOURCE MONITOR (cost guardrail) ────────────────────────
CREATE RESOURCE MONITOR IF NOT EXISTS RM_LAKEHOUSE_MONTHLY
  WITH CREDIT_QUOTA = 500
  FREQUENCY         = MONTHLY
  START_TIMESTAMP   = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_TRANSFORM  SET RESOURCE_MONITOR = RM_LAKEHOUSE_MONTHLY;
ALTER WAREHOUSE WH_ANALYTICS  SET RESOURCE_MONITOR = RM_LAKEHOUSE_MONTHLY;
ALTER WAREHOUSE WH_CORTEX     SET RESOURCE_MONITOR = RM_LAKEHOUSE_MONTHLY;
